### ISSUE TITLE
Generated workflow.yaml file is invalid for v1.1

### ISSUE THREAD

**Issue by ibreschi** [Deepomatic/deepocli#162]
The command `deepo platform app create ABC` generates a workflow.yaml that is not anymore valid. 
https://github.com/Deepomatic/deepocli/blob/360672d4ecab615e6eebfbf90da9363c92702b6e/deepomatic/cli/lib/platform.py#L90

Make it valid for the new version

**Comment by maingoh** [comment]
We don't generate it anymore, the user should provide it
