### ISSUE TITLE
Installation with Python 3.5 fails

### ISSUE THREAD

**Issue by vdel** [Deepomatic/deepocli#168]
In an environment with Python 3.5 (e.g. Ubuntu 16.04)

```
pip3 install deepomatic-cli
```

eventually leads to:

```
ERROR: Package 'zipp' requires a different Python: 3.5.2 not in '>=3.6'
```

The problem is that we have a dependency `zipp>=0.5` and that apparently the latest version requires Python 3.6.

Running `pip3 install zipp==0.5` prior to running `pip3 install deepomatic-cli` solves the problem.

**Comment by maingoh** [comment]
We don't have any direct requirement for zipp, do you know which library requires zipp ?

**Comment by vdel** [comment]
> do you know which library requires zipp ?

Eeeeh.... no.

**Comment by maingoh** [comment]
Python 3.5 is a bit too old, please upgrade your python installation and feel free to reopen if the issue occurs again :)

**Comment by maingoh** [comment]
Close by #215
