### ISSUE TITLE
JSONDecodeError on BadStatus exception during image upload

### ISSUE THREAD

**Issue by romyli** [Deepomatic/deepocli#201]
Command used: `deepo platform add-images -o org -p project -i path/to/image.jpeg`
It raises an error, seems the status code is in [400;500] and the print of the error json content fails.

![image](https://user-images.githubusercontent.com/49392003/113841969-8bb75780-9792-11eb-89ec-95074450f65c.png)

https://github.com/Deepomatic/deepocli/blob/master/deepomatic/cli/thread_base.py#L223

**Comment by maingoh** [comment]
According to the code it is a 4xx. Technically the field `error` should be set, but we could just print the response content; without trying to print the `error` subfield only.
