### ISSUE TITLE
Allow customizing the upstream API endpoint

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/deepocli#24]
Currently the API endpoint is never specified: we rely on the default behavior of the `deepomatic-api` client, which is `https://api.deepomatic.com`.

**Comment by maingoh** [comment]
It should work with DEEPOMATIC_API_URL env var

**Comment by thomas-riccardi** [comment]
The `DEEPOMATIC_API_URL` env var only exists since v0.8.1 of `deepomatic-api` client: https://github.com/Deepomatic/deepomatic-client-python/commit/a8e4fedb984494cec2684b0ee1f10930661068c3

We should bump it here: https://github.com/Deepomatic/deepocli/blob/b7ef082d5ad67417fbeccfb21e138b42fe02e00d/requirements.txt#L6
